name: Deploy React App with Docker

on:
  push:
    branches: [ "main" ]  # jab bhi main branch pe push hoga

jobs:
  build-deploy:
    runs-on: self-hosted  # Self-hosted runner use kar rahe hain

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag swiggy:latest

      - name: Deploy on Server
        run: |
          docker stop swiggy || true
          docker rm swiggy || true
          docker run -d --name swiggy -p 8080:3000 swiggy:latest
