name: Deploy React App with Docker

on:
  push:
    branches: [ "main" ]  # jab bhi main branch pe push hoga

jobs:
  build-deploy:
    runs-on: self-hosted  # Self-hosted runner use kar rahe hain

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag swiggy:latest
          docker tag react-app:latest ravikant21/swiggy:latest
          docker push ravikant21/swiggy:latest

      - name: Deploy on Server
        run: |
          docker pull ravikant21/swiggy:latest
          docker stop swiggy || true
          docker rm swiggy || true
          docker run -d --name react-app -p 8080:3000 ravikant21/swiggy:latest
